language: c

sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

addons:
  apt:
    libyaml-dev
    libssl-dev

# For now...
branches:
  only:
    - feature/getdns-subbuild

before_install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew update >/dev/null; fi

install:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install libyaml; fi
  - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install openssl; fi

before_script:
  - autoreconf -vfi
  - mkdir build
  - cd build
  - if [ "$TRAVIS_OS_NAME" = osx ]; then WITH_SSL="--with-ssl=/use/local/opt/openssl"; fi
  - ../configure --enable-stub-only --without-libidn --without-libidn2 $WITH_SSL
