language: c

sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

# Dependencies. We need libyaml and libssl.
# Both are installed in the base Travis image.

# For now...
branches:
  only:
    - feature/travis

before_script:
  - autoreconf -vfi
  - mkdir build
  - cd build
  - if [ "$TRAVIS_OS_NAME" = osx ]; then WITH_SSL="--with-ssl=/usr/local/opt/openssl"; fi
  - ../configure --enable-stub-only --without-libidn --without-libidn2 $WITH_SSL

script:
  - make
