language: c

sudo: false

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

# Use macOS Sierra
osx_image: xcode9.2

# See if we can get xenial. This may not work.
# See https://github.com/travis-ci/travis-ci/issues/7260
dist: xenial

# Dependencies. We need libyaml and libssl.
# Both are installed in the base Travis image.

before_script:
  - autoreconf -vfi
  - mkdir build
  - cd build
  - if [ "$TRAVIS_OS_NAME" = osx ]; then WITH_SSL="--with-ssl=/usr/local/opt/openssl"; fi
  - ../configure --enable-stub-only --without-libidn --without-libidn2 $WITH_SSL

script:
  - make
